name: dockerize and push

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  dockerize:
    name: dockerize
    runs-on: [ubuntu-latest]
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    outputs:
      environment: ${{ steps.variables.outputs.environment }}
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          clean: false

      - name: Create Manifest
        run: ./gradlew manifest

      - name: Docker Login
        if: github.event_name == 'push'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Build and Push
        if: github.event_name == 'push'
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          SERVICE: ${{ secrets.SERVICE }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $DOCKERHUB_USERNAME/$SERVICE:$IMAGE_TAG -t $DOCKERHUB_USERNAME/$SERVICE:latest .
          docker push $DOCKERHUB_USERNAME/$SERVICE:$IMAGE_TAG
          docker push $DOCKERHUB_USERNAME/$SERVICE:latest
